name: opentofu_portable test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'opentofu.portable/**'

jobs:
  Test-opentofu_portable-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: 🦺 Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: 📦 Pack Chocolatey Package
        run: choco pack opentofu.portable/opentofu.portable.nuspec
      - name: 🚀 Install Chocolatey Package
        run: choco install opentofu.portable -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"
      - name: 🚨 Test opentofu
        run: tofu version