name: Zoom VDI plugin test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'Zoom-VDI-Universal-Plugin/**'

jobs:
  Test-zoom-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: 🦺 Install validation extension
        run: choco install chocolatey-community-validation.extension -y
      - name: 📦 Pack Chocolatey Package
        run: choco pack Zoom-VDI-Universal-Plugin/zoom-vdi-universal-plugin.nuspec
      - name: 🚀 Install Chocolatey Package
        run: choco install zoom-vdi-universal-plugin -y --debug --verbose --source "'.;https://community.chocolatey.org/api/v2/'"